# General Settings

title: YOI - the Yoshino Frontend Component Library
description: A quick-to-learn, yet powerful set of elements and utilities for building and designing web pages directly in the browser.
url: "https://yoshino-digital.github.io/yoi/"
github_username: yoshino-digital

# Build Settings

baseurl: ""
markdown: kramdown
include: ['_pages']
exclude: ['Gemfile','Gemfile.lock']

# Learn more about configuring jekyll for github pages:
# http://downtothewire.io/2015/08/15/configuring-jekyll-for-user-and-project-github-pages/
