# General Settings

title: YOI - the Yoshino Frontend Foundation
description: An easy to learn, yet powerful set of modules to build and design web pages directly in the browser.
url: "https://yoshino-digital.github.io"
github_username: yoshino-digital

# Site Variables

icon: "http://cdn.yoshino.digital/svg.php?id=icon-"

# Build Settings

baseurl: ""
markdown: kramdown
include: ['_pages']
exclude: ['Gemfile','Gemfile.lock']

# Learn more about configuring jekyll for github pages:
# http://downtothewire.io/2015/08/15/configuring-jekyll-for-user-and-project-github-pages/
