# General Settings

title: YOI - the Yoshino Frontend Component Library
description: A quick-to-learn, yet powerful set of elements and utilities for building and designing web pages directly in the browser.
url: "https://yoshino-digital.github.io/yoi/"
plugins_dir:
  - jekyll-sitemap

# Build Settings

baseurl: ""
markdown: kramdown
include: ['_pages']
exclude: ['Gemfile','Gemfile.lock']
incremental: true
livereload: true

# Github

github_username: yoshino-digital
repository: yoshino-digital/yoi

# Learn more about configuring jekyll for github pages:
# http://downtothewire.io/2015/08/15/configuring-jekyll-for-user-and-project-github-pages/
# https://help.github.com/articles/repository-metadata-on-github-pages/
